# Chapter 5. The Basics of NumPy Arrays

참고: NumPy Array Attributes

In [8]:
import numpy as np
rng = np.random.default_rng(seed=1701)

x1 = rng.integers(10, size=6)  # one-dimensional array
x2 = rng.integers(10, size=(3, 4))  # two-dimensional array
x3 = rng.integers(10, size=(3, 4, 5))  # three-dimensional array

print("x3 ndim", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)
print("x3 dtype", x3.dtype)

x3 ndim 3
x3 shape (3, 4, 5)
x3 size 60
x3 dtype int64


## 5.1 Creating NumPy Arrays

In [7]:
import numpy as np

# 1. python list creating
arr1 = np.array([1, 2, 3, 4, 5])
print("1D array:", arr1)

# 2. 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array:\n", arr2)

# 3. special array creation
zeros = np.zeros((3, 4))    # 3x4 령행렬
ones = np.ones((2, 3))      # 2x3 1행렬
identity = np.eye(3)        # 3x3 단위행렬
empty = np.empty((2, 2))    # 초기화되지 않은 배렬

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Identity:\n", identity)

# 4. range-based generation
range_arr = np.arange(0, 10, 2)     # 0부터 10까지 2씩
linspace_arr = np.linspace(0, 1, 5) # 0부터 1까지 5등분

print("Arange:", range_arr)
print("Linspace:", linspace_arr)

# 5. Random Number Generation
random_arr = np.random.random((2, 3))       # 0~1 균등분포
normal_arr = np.random.normal(0, 1, 5)      # 정규분포
int_arr = np.random.randint(0, 10, (2, 3))  # 정수 난수

print("Random:", random_arr)
print("Normal:", normal_arr)
print("Integers:", int_arr)

# 6. Specifying Data Types
arr_int32 = np.array([1, 2, 3], dtype=np.int32)
arr_float64 = np.array([1, 2, 3], dtype=np.float64)

print("int32:", arr_int32.dtype)
print("float64:", arr_float64.dtype)

1D array: [1 2 3 4 5]
2D array:
 [[1 2 3]
 [4 5 6]]
Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random: [[0.08078838 0.45413276 0.70950238]
 [0.65363841 0.96961031 0.79851424]]
Normal: [ 0.78957241 -0.34622217 -0.2968375   2.25831149 -1.18852679]
Integers: [[6 2 3]
 [8 5 4]]
int32: int32
float64: float64


## 5.2 NumPy standard data types

In [9]:
# 주요 데이터 타입 정리
# int8, int16, int32, int64
# uint8, uint16, uint32, uint64
# float16, float32, float64
# complex64, complex128
# bool

# 타입 변환
arr = np.array([1, 2, 3])
arr_float = arr.astype(np.float64)
print(arr_float)

[1. 2. 3.]


## 5.3 NumPy array attribute

In [10]:
import numpy as np

# 1D, 2D, 3D 배열 생성
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("=== Array attribute ===")
print(f"arr1d.ndim: {arr1d.ndim}")      # 차원 수
print(f"arr1d.shape: {arr1d.shape}")    # 각 차원의 크기
print(f"arr1d.size: {arr1d.size}")      # 전체 요소 수
print(f"arr1d.dtype: {arr1d.dtype}")    # 자료 타입

print(f"\narr2d.ndim: {arr2d.ndim}")
print(f"arr2d.shape: {arr2d.shape}")
print(f"arr2d.size: {arr2d.size}")

print(f"\narr3d.ndim: {arr3d.ndim}")
print(f"arr3d.shape: {arr3d.shape}")
print(f"arr3d.size: {arr3d.size}")

=== Array attribute ===
arr1d.ndim: 1
arr1d.shape: (5,)
arr1d.size: 5
arr1d.dtype: int64

arr2d.ndim: 2
arr2d.shape: (2, 3)
arr2d.size: 6

arr3d.ndim: 3
arr3d.shape: (2, 2, 2)
arr3d.size: 8


## 5.4 Array Indexing and Slicing

In [15]:
import numpy as np

# 1D array
arr1d = np.arange(10)
print("original:", arr1d)

print("=== 1D array indexing ===")
print(f"arr1d[0]: {arr1d[0]}")
print(f"arr1d[-1]: {arr1d[-1]}")
print(f"arr1d[3:7]: {arr1d[3:7]}")
print(f"arr1d[:5]: {arr1d[:5]}")
print(f"arr1d[5:]: {arr1d[5:]}")
print(f"arr1d[::2]: {arr1d[::2]}")      # 2칸씩
print(f"arr1d[::-1]: {arr1d[::-1]}")    # 거꾸로

# 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\noriginal 2D array:\n", arr2d)

print("\n=== 2D indexing ===")
print(f"arr2d[0, 0]: {arr2d[0, 0]}")
print(f"arr2d[1, 2]: {arr2d[1, 2]}")
print(f"arr2d[0, :]: {arr2d[0, :]}")    # 1행 전체
print(f"arr2d[:, 0]: {arr2d[:, 0]}")    # 1열 전체
print(f"arr2d[1:3, 1:3]: {arr2d[1:3, 1:3]}")

# 3D array
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D array original:\n", arr3d)

print("\n=== 3D indexing ===")
print(f"arr3d[0, 1, 0]: {arr3d[0, 1, 0]}")
print(f"arr3d[1, :, :]:\n{arr3d[1, :, :]}")


original: [0 1 2 3 4 5 6 7 8 9]
=== 1D array indexing ===
arr1d[0]: 0
arr1d[-1]: 9
arr1d[3:7]: [3 4 5 6]
arr1d[:5]: [0 1 2 3 4]
arr1d[5:]: [5 6 7 8 9]
arr1d[::2]: [0 2 4 6 8]
arr1d[::-1]: [9 8 7 6 5 4 3 2 1 0]

original 2D array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

=== 2D indexing ===
arr2d[0, 0]: 1
arr2d[1, 2]: 6
arr2d[0, :]: [1 2 3]
arr2d[:, 0]: [1 4 7]
arr2d[1:3, 1:3]: [[5 6]
 [8 9]]

3D array original:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

=== 3D indexing ===
arr3d[0, 1, 0]: 3
arr3d[1, :, :]:
[[5 6]
 [7 8]]


*Array Copy vs View*

In [18]:
# 중요! NumPy slicing 뷰(View)를 반환
arr = np.arange(10)
print("original: ", arr)

# slice - it is view
slice_view = arr[2:5]
slice_view[0] = 100
print("Original after modifying the view:", arr)

# making copy data
arr = np.arange(10)
copy_arr = arr[2:5].copy()
copy_arr[0] = 100
print("Original after modifying the copy:", arr)

original:  [0 1 2 3 4 5 6 7 8 9]
Original after modifying the view: [  0   1 100   3   4   5   6   7   8   9]
Original after modifying the copy: [0 1 2 3 4 5 6 7 8 9]


## 5.5 Array Reshape and Combine/Split

In [27]:
import numpy as np

# Reshape
arr = np.arange(12)
print("Original:", arr)

# 1D -> 2D
arr_2d = arr.reshape(3, 4)
print("3x4 reshape:\n", arr_2d)

# 1D -> 3D
arr_3d = arr.reshape(2, 3, 2)
print("2x3x2 reshape:\n", arr_3d)

# -1 automatically calculate
auto_reshape = arr.reshape(2, -1)
print("auto reshape (2, -1):\n", auto_reshape)

# Transpose
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("original:\n", arr)
print("transpose:\n", arr.T)

# array concatenate
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

## 수평결합
h_stack = np.concatenate([arr1, arr2])
print("수평결합:", h_stack)

## 수직결합
v_stack = np.vstack([arr1, arr2])
print("수직결합:", v_stack)

# array spliting
arr = np.arange(10)
splits = np.split(arr, [3, 7])
print("result spliting:", splits)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
3x4 reshape:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
2x3x2 reshape:
 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
auto reshape (2, -1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
original:
 [[1 2 3]
 [4 5 6]]
transpose:
 [[1 4]
 [2 5]
 [3 6]]
수평결합: [1 2 3 4 5 6]
수직결합: [[1 2 3]
 [4 5 6]]
result spliting: [array([0, 1, 2]), array([3, 4, 5, 6]), array([7, 8, 9])]
