# Chapter 6. Computation on NumPy Arrays:Universal Functions

## 6.1 The Slowness of Loops

Python's default implementation (CPython) processes some operations very slowly. This is partly due to the dynamic and interpreted nature of the language. Because the types are flexible, sequences of operations cannot be compiled into efficient machine code like in languages ​​such as C or Fortran.

In [3]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

values = rng.integers(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[9 4 1 3 8]
[0.11111111 0.25       1.         0.33333333 0.125     ]


This implementation feels natural to those with a C or Java background. However, if you measure the execution time for large inputs, you will find that it is very slow:

In [4]:
big_array = rng.integers(1, 100, size=1_000_000)
%timeit compute_reciprocals(big_array)

1.11 s ± 49.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## 6.2 Introducing Ufuncs (Ufuncs 소개)

NumPy provides a convenient interface for these statically typed compiled routines. This is called a vectorized operation.

In [5]:
# vectorized operation
%timeit (1.0 / big_array)

2.39 ms ± 81.5 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


Vectorized NumPy operations are implemented through ufunc. ufunc supports operations between arrays as well as between scalars and arrays.

In [7]:
# 스칼라와 배렬연산
np.array(5) / np.arange(1, 6)

# 다차원 배렬연산
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

*Key point: Whenever you encounter a Python loop, consider whether it can be replaced with a vectorized representation!*

## 6.3 Exploring NumPy's Ufuncs

Ufuncs는 단항(unary) 과 이항(binary) 두 가지 형태로 존재합니다.

* Array Arithmetic

In [17]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

print("-x     =", -x)
print("x ** 2 =", x ** 2)
print("x % 2  =", x % 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x     = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2  = [0 1 0 1]


* Absolute Value

In [ ]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)              # array([2, 1, 0, 1, 2])
np.absolute(x)      # array([2, 1, 0, 1, 2])
np.abs(x)           # array([2, 1, 0, 1, 2])

# 복소수크기
x = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
abs(x)

array([5., 5., 2., 1.])

* Trigonometric Functions (삼각함수)

In [27]:
theta = np.linspace(0, np.pi, 3)
print("theta      =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

# 거꿀삼각함수
x = [-1, 0, 1]
print("arcsin(x) =", np.arcsin(x))
print("arccos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

theta      = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]
