# Chapter 12: Structured Data: NumPy's Structured Arrays

## 12.1 Structured Arrays introduction

* Limitations of Standard NumPy Arrays

In [3]:
import numpy as np

arr = np.array([1, 2, 3])           # 모두 정수
arr2 = np.array([1.5, 2.3, 3.1])    # 모두 실수

arr3 = np.array([1, "hello", 3.0])
print(arr3)                         # 타입이 섞이면 모두 문자렬로 변환됨

['1' 'hello' '3.0']


* The Need for Structured Arrays

In [ ]:
# 이름, 나이, 몸무게를 함께 저장하고 싶다면?
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

# 세 개의 배열을 따로 관리해야 하는 불편함

## 12.2 Creating Structured Arrays

* Method 1: Specify dtype as a dictionary

In [5]:
import numpy as np

# dtype 정의: names(필드명), formats(자료 타입)
data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})

print(data.dtype)
# [('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]

# 자료할당
data['name'] = ['Alice', 'Bob', 'Cathy', 'Doug']
data['age'] = [25, 45, 37, 19]
data['weight'] = [55.0, 85.5, 68.0, 61.5]

print(data)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


| 코드 | 의미 | Python 타입 |
|------|------|-------------|
| `'b'` | Byte | `int` |
| `'i'` | Signed integer | `int` |
| `'u'` | Unsigned integer | `int` |
| `'f'` | Floating point | `float` |
| `'c'` | Complex floating point | `complex` |
| `'S'`, `'a'` | String (bytes) | `bytes` |
| `'U'` | Unicode string | `str` |
| `'V'` | Raw data (void) | `-` |

* Method 2: Specify as a list of tuples

In [6]:
data2 = np.zeros(4, dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f8')])
print(data2.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


* Method 3: Comma-separated strings

In [ ]:
data3 = np.zeros(4, dtype='U10, i4, f8')
print(data3.dtype)
# [('f0', '<U10'), ('f1', '<i4'), ('f2', '<f8')]
# 필드명이 자동으로 f0, f1, f2로 지정됨

[('f0', '<U10'), ('f1', '<i4'), ('f2', '<f8')]


## 12.3 Accessing Structured Arrays

In [13]:
# field access
print(data['name'])
print(data['age'])
print(data['weight'])

# row access
print(data[0])
print(data[-1]['name'])

# Boolean masking
print(data[data['age'] < 30]['name'])

['Alice' 'Bob' 'Cathy' 'Doug']
[25 45 37 19]
[55.  85.5 68.  61.5]
('Alice', 25, 55.0)
Doug
['Alice' 'Doug']


## 12.4 Advanced Compound Types

* Types containing arrays or matrices

In [16]:
# 3x3 행렬을 포함하는 데이터 타입
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3, 3))])
X = np.zeros(1, dtype=tp)

print(X[0])

print(X['mat'][0])

(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## 12.5 Record Arrays: Structured Arrays with a Twist

In [ ]:
# 일반 구조화된 배렬
data = np.zeros(4, dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f8')])
data['name'] = ['Alice', 'Bob', 'Cathy', 'Doug']

# 레코드 배렬로 변환 (필드를 속성처럼 접근 가능)
data_rec = data.view(np.recarray)

# 속성처럼 접근 (더 간결!)
print(data_rec.name)
print(data_rec.age)

# 단점: 약간의 성능 저하
%timeit data['name']        # 약 121 ns
%timeit data_rec['name']    # 약 2.41 us (약 20배 느림)
%timeit data_rec.name       # 약 3.98 us (약 33배 느림)

['Alice' 'Bob' 'Cathy' 'Doug']
[0 0 0 0]
67.5 ns ± 28.6 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
915 ns ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
1.67 μs ± 13.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
